// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClenD6iZ8nDTmEc5_wN-H3ryhX5iSE26g',
    appId: '1:105980073132:web:5fd0979236c227c95c3b09',
    messagingSenderId: '105980073132',
    projectId: 'simply-delivery-39a77',
    authDomain: 'simply-delivery-39a77.firebaseapp.com',
    storageBucket: 'simply-delivery-39a77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXC84nUmcuYw4peuwZps84g-ayZRJ5p9A',
    appId: '1:105980073132:android:34a14b9ab23cbf1c5c3b09',
    messagingSenderId: '105980073132',
    projectId: 'simply-delivery-39a77',
    storageBucket: 'simply-delivery-39a77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Q1TgMt_6suRnfmik0qyhDTOTMZnK-VU',
    appId: '1:105980073132:ios:30095fa694d3157a5c3b09',
    messagingSenderId: '105980073132',
    projectId: 'simply-delivery-39a77',
    storageBucket: 'simply-delivery-39a77.appspot.com',
    iosClientId: '105980073132-1bq03hbtl7mq8enlnlggseo2id7qdjo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Q1TgMt_6suRnfmik0qyhDTOTMZnK-VU',
    appId: '1:105980073132:ios:30095fa694d3157a5c3b09',
    messagingSenderId: '105980073132',
    projectId: 'simply-delivery-39a77',
    storageBucket: 'simply-delivery-39a77.appspot.com',
    iosClientId: '105980073132-1bq03hbtl7mq8enlnlggseo2id7qdjo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.talabat',
  );
}
